linux: Disable GCC plug-ins in LKFT config fragment in 5.14/mainline/next
The configuration set to yes has led to the kernel failing to
build on (oddly enough) newer systems:

| In file included from /poky/build/tmp-lkft-glibc/work/am57xx_evm-linaro-linux-gnueabi/linux-generic-mainline/5.14+gitAUTOINC+7d2a07b769-r0/recipe-sysroot-native/usr/bin/arm-linaro-linux-gnueabi/../../lib/arm-linaro-linux-gnueabi/gcc/arm-linaro-linux-gnueabi/7.3.0/plugin/include/gcc-plugin.h:28,
|                  from /poky/build/tmp-lkft-glibc/work-shared/am57xx-evm/kernel-source/scripts/gcc-plugins/gcc-common.h:7,
|                  from /poky/build/tmp-lkft-glibc/work-shared/am57xx-evm/kernel-source/scripts/gcc-plugins/arm_ssp_per_task_plugin.c:3:
| /poky/build/tmp-lkft-glibc/work/am57xx_evm-linaro-linux-gnueabi/linux-generic-mainline/5.14+gitAUTOINC+7d2a07b769-r0/recipe-sysroot-native/usr/bin/arm-linaro-linux-gnueabi/../../lib/arm-linaro-linux-gnueabi/gcc/arm-linaro-linux-gnueabi/7.3.0/plugin/include/system.h:691:10: fatal error: libiberty.h: No such file or directory
|  #include "libiberty.h"
|           ^~~~~~~~~~~~~
| compilation terminated.
| make[3]: *** [/poky/build/tmp-lkft-glibc/work-shared/am57xx-evm/kernel-source/scripts/gcc-plugins/Makefile:48: scripts/gcc-plugins/arm_ssp_per_task_plugin.so] Error 1
| make[2]: *** [/poky/build/tmp-lkft-glibc/work-shared/am57xx-evm/kernel-source/scripts/Makefile.build:514: scripts/gcc-plugins] Error 2

This problem has been present since December 2020, a little
after v5.10 was released in mainline. So all kernels after
that time have failed for Arm 32-bits machines.

This can be reproduced under Docker, and currently affects our
Jenkins and Gitlab builds, which run on clean environments
under Docker (two different images and base distros).

On an older system, Hackbox, with uncontrolled sources
installed on the host's root file system, this is not a
problem at all, as the two configs do not get selected.

This kernel configuration works:

  CONFIG_HAVE_GCC_PLUGINS=y

whereas this set of configs fail:

  CONFIG_HAVE_GCC_PLUGINS=y
  CONFIG_GCC_PLUGINS=y
  # CONFIG_GCC_PLUGIN_CYC_COMPLEXITY is not set
  # CONFIG_GCC_PLUGIN_LATENT_ENTROPY is not set
  # CONFIG_GCC_PLUGIN_RANDSTRUCT is not set
  CONFIG_GCC_PLUGIN_ARM_SSP_PER_TASK=y

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>

(Cherry-picked from commit 85b14248936851068ffc53bdcbe44ec0444a41de)