meta: conf: distro: lkft: make kirkstone build
Build fails with this error:

ERROR: ParseError at
/builddir/meta-lkft/meta/conf/distro/lkft.conf:1:
Could not include required file conf/distro/include/rpb.inc

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>